# Initializes a new nodejs project with docker

version: '3.7'
services:
  app:
    image: node:19.8.1
    container_name: discord-bot-${SYMBOL}
    restart: unless-stopped
    working_dir: /var/www
    command: bash -c "npm install --no-audit && npm run prod"
    volumes:
      - ./:/var/www
    networks:
      - app

networks:
  app:
    driver: bridge
