services:
  crypto-bot-sol:
    image: node:20.0-bullseye-slim
    working_dir: /var/www
    command: sh -c "chmod +x docker-secrets.sh && ./docker-secrets.sh && npm install --no-audit && npm run prod"
    volumes:
      - ./:/var/www
    environment:
      SYMBOL: sol
    secrets:
      - DATADOG_API_KEY
      - DISCORD_GUILD_ID
      - SOL_BOT_ID
      - SOL_BOT_TOKEN
      - ZBC_BOT_ID
      - ZBC_BOT_TOKEN
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

  crypto-bot-zbc:
    image: node:20.0-bullseye-slim
    working_dir: /var/www
    command: sh -c "chmod +x docker-secrets.sh && ./docker-secrets.sh && npm install --no-audit && npm run prod"
    volumes:
      - ./:/var/www
    environment:
      SYMBOL: zbc
    secrets:
      - DATADOG_API_KEY
      - DISCORD_GUILD_ID
      - SOL_BOT_ID
      - SOL_BOT_TOKEN
      - ZBC_BOT_ID
      - ZBC_BOT_TOKEN
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

secrets:
  DATADOG_API_KEY:
    external: true
  DISCORD_GUILD_ID:
    external: true
  SOL_BOT_ID:
    external: true
  SOL_BOT_TOKEN:
    external: true
  ZBC_BOT_ID:
    external: true
  ZBC_BOT_TOKEN:
    external: true
